a=input ('digite algo')
print ('o tipo primitivo de {} é'.format(a), type(a))
print('só tem espaços?',a.isspace())
print('é um número?',a.isnumeric())
print('é alfabetico?',a.isalpha())
print('é alfanumerico?',a.isalnum())
print('está em maiusculo?',a.isupper())
print('está em minusculo?',a.islower())
print('está capitalizada?',a.istitle())

